rem
rem Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5
rem
rem Copyright (C) 2022 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>
rem
rem Batch to compile all tests
rem

hbmk2 HEventFilter            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 HEventFilter2           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QBoxLayout1             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QBoxLayout2             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QBoxLayout3             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QBoxLayout4             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QButtonGroup            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCalendarWidget         %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCheckBox1              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCheckBox2              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCheckBox3              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QColorDialog1           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QColorDialog2           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCombobox               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCommandLinkButton1     %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCommandLinkButton2     %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QCompleter              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDateEdit               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDateTimeEdit           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDesktopWidget          %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDial1                  %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDial2                  %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDialog                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDockWidget             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QDoubleSpinBox          %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QErrorMessage           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFileDialog1            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFileDialog2            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFocusFrame             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFontComboBox           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFontDialog             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFormLayout1            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFormLayout2            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QFormLayout3            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QGraphicsEffect         %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QGridLayout             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QGroupBox               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QHBoxLayout             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QInputDialog            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QLabel1                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QLabel2                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QLabel3                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QLCDNumber              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QListView               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMainWindow             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMdiArea                %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMenu1                  %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMenu2                  %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMessageBox1            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMessageBox2            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QMovie                  %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPlainTextEdit          %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QProgressBar            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QProgressDialog         %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton1            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton2            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton3            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton4            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton5            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QPushButton6            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QRadioButton1           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QRadioButton2           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QRubberBand             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QScrollBar              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QShortcut               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QSlider                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QSpinBox                %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QStatusBar              %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QTableWidget1           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QTableWidget2           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QTableWidget3           %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QTimeEdit               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolBox1               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolBox2               %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolButton1            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolButton2            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolButton3            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QToolButton4            %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QTreeWidget             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QVBoxLayout             %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QWidget                 %1 %2 %3 ..\..\qt5xhb.hbc
hbmk2 QWizard                 %1 %2 %3 ..\..\qt5xhb.hbc
