/*

  Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5

  Copyright (C) 2018 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content was created using a source code generator
*/

#ifndef QMETADATAREADERCONTROLSLOTS_H
#define QMETADATAREADERCONTROLSLOTS_H

#include <QObject>
#include <QCoreApplication>
#include <QString>

#include <QMetaDataReaderControl>

#include "qt5xhb_common.h"
#include "qt5xhb_macros.h"
#include "qt5xhb_signals.h"

class QMetaDataReaderControlSlots: public QObject
{
  Q_OBJECT
  public:
  QMetaDataReaderControlSlots(QObject *parent = 0);
  ~QMetaDataReaderControlSlots();
  public slots:
  void metaDataChanged();
  void metaDataChanged( const QString & key, const QVariant & value );
  void metaDataAvailableChanged( bool available );
};

#endif /* QMETADATAREADERCONTROLSLOTS_H */
