# QtAndroidExtras
OBJECTS_QTANDROIDEXTRAS =
OBJECTS_QTANDROIDEXTRAS += $(QT5XHB_OBJ_DIR)/QAndroidActivityResultReceiver$(OBJEXT)
OBJECTS_QTANDROIDEXTRAS += $(QT5XHB_OBJ_DIR)/QAndroidJniEnvironment$(OBJEXT)
OBJECTS_QTANDROIDEXTRAS += $(QT5XHB_OBJ_DIR)/QAndroidJniObject$(OBJEXT)
OBJECTS_QTANDROIDEXTRAS += $(QT5XHB_OBJ_DIR)/QtAndroid$(OBJEXT)
OBJECTS_QTANDROIDEXTRAS += $(QT5XHB_OBJ_DIR)/QtAndroidExtrasVersion$(OBJEXT)
