# QtPurchasing
OBJECTS_QTPURCHASING =
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QInAppProduct$(OBJEXT)
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QInAppStore$(OBJEXT)
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QInAppStoreSlots$(OBJEXT)
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QInAppStoreSlotsMoc$(OBJEXT)
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QInAppTransaction$(OBJEXT)
OBJECTS_QTPURCHASING += $(QT5XHB_OBJ_DIR)/QtPurchasingVersion$(OBJEXT)
