# QtQuickWidgets
OBJECTS_QTQUICKWIDGETS =
OBJECTS_QTQUICKWIDGETS += $(QT5XHB_OBJ_DIR)/QQuickWidget$(OBJEXT)
OBJECTS_QTQUICKWIDGETS += $(QT5XHB_OBJ_DIR)/QQuickWidgetSlots$(OBJEXT)
OBJECTS_QTQUICKWIDGETS += $(QT5XHB_OBJ_DIR)/QQuickWidgetSlotsMoc$(OBJEXT)
