# QtScriptTools
OBJECTS_QTSCRIPTTOOLS =
OBJECTS_QTSCRIPTTOOLS += $(QT5XHB_OBJ_DIR)/QScriptEngineDebugger$(OBJEXT)
OBJECTS_QTSCRIPTTOOLS += $(QT5XHB_OBJ_DIR)/QScriptEngineDebuggerSlots$(OBJEXT)
OBJECTS_QTSCRIPTTOOLS += $(QT5XHB_OBJ_DIR)/QScriptEngineDebuggerSlotsMoc$(OBJEXT)
