# QtSerialPort
OBJECTS_QTSERIALPORT =
OBJECTS_QTSERIALPORT += $(QT5XHB_OBJ_DIR)/QSerialPort$(OBJEXT)
OBJECTS_QTSERIALPORT += $(QT5XHB_OBJ_DIR)/QSerialPortSlots$(OBJEXT)
OBJECTS_QTSERIALPORT += $(QT5XHB_OBJ_DIR)/QSerialPortSlotsMoc$(OBJEXT)
OBJECTS_QTSERIALPORT += $(QT5XHB_OBJ_DIR)/QSerialPortInfo$(OBJEXT)
