# QtSvg
OBJECTS_QTSVG =
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QGraphicsSvgItem$(OBJEXT)
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QSvgGenerator$(OBJEXT)
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QSvgRenderer$(OBJEXT)
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QSvgRendererSlots$(OBJEXT)
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QSvgRendererSlotsMoc$(OBJEXT)
OBJECTS_QTSVG += $(QT5XHB_OBJ_DIR)/QSvgWidget$(OBJEXT)
