# QtWebChannel
OBJECTS_QTWEBCHANNEL =
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QQmlWebChannel$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannelAbstractTransport$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannelAbstractTransportSlots$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannelAbstractTransportSlotsMoc$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannel$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannelSlots$(OBJEXT)
OBJECTS_QTWEBCHANNEL += $(QT5XHB_OBJ_DIR)/QWebChannelSlotsMoc$(OBJEXT)
