/*

  Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5

  Copyright (c) 2024 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content was created using a source code generator
*/

#ifndef QWEBENGINEVIEWSLOTS_H
#define QWEBENGINEVIEWSLOTS_H

#include <QtCore/QObject>
#include <QtCore/QCoreApplication>
#include <QtCore/QString>

#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
#include <QtWebEngineWidgets/QWebEngineView>
#endif

#include "qt5xhb_common.hpp"
#include "qt5xhb_macros.hpp"
#include "qt5xhb_utils.hpp"
#include "qt5xhb_signals.hpp"

class QWebEngineViewSlots : public QObject
{
  Q_OBJECT
public:
  QWebEngineViewSlots(QObject *parent = 0);
  ~QWebEngineViewSlots();
public slots:
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void loadStarted();
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void loadProgress(int progress);
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void loadFinished(bool b);
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void titleChanged(const QString &title);
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void selectionChanged();
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void urlChanged(const QUrl &url);
#endif
#if (QT_VERSION >= QT_VERSION_CHECK(5, 4, 0))
  void iconUrlChanged(const QUrl &url);
#endif
};

#endif /* QWEBENGINEVIEWSLOTS_H */
