/*

  Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5

  Copyright (C) 2019 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content was created using a source code generator
*/

#ifndef QT5XHB_MACROS_QTSCRIPT_H
#define QT5XHB_MACROS_QTSCRIPT_H

#define ISQSCRIPTABLE(n)                                    _qt5xhb_isObjectDerivedFrom(n,"QScriptable")
#define ISQSCRIPTCLASS(n)                                   _qt5xhb_isObjectDerivedFrom(n,"QScriptClass")
#define ISQSCRIPTCLASSPROPERTYITERATOR(n)                   _qt5xhb_isObjectDerivedFrom(n,"QScriptClassPropertyIterator")
#define ISQSCRIPTCONTEXT(n)                                 _qt5xhb_isObjectDerivedFrom(n,"QScriptContext")
#define ISQSCRIPTCONTEXTINFO(n)                             _qt5xhb_isObjectDerivedFrom(n,"QScriptContextInfo")
#define ISQSCRIPTENGINE(n)                                  _qt5xhb_isObjectDerivedFrom(n,"QScriptEngine")
#define ISQSCRIPTENGINEAGENT(n)                             _qt5xhb_isObjectDerivedFrom(n,"QScriptEngineAgent")
#define ISQSCRIPTEXTENSIONPLUGIN(n)                         _qt5xhb_isObjectDerivedFrom(n,"QScriptExtensionPlugin")
#define ISQSCRIPTPROGRAM(n)                                 _qt5xhb_isObjectDerivedFrom(n,"QScriptProgram")
#define ISQSCRIPTSTRING(n)                                  _qt5xhb_isObjectDerivedFrom(n,"QScriptString")
#define ISQSCRIPTSYNTAXCHECKRESULT(n)                       _qt5xhb_isObjectDerivedFrom(n,"QScriptSyntaxCheckResult")
#define ISQSCRIPTVALUE(n)                                   _qt5xhb_isObjectDerivedFrom(n,"QScriptValue")
#define ISQSCRIPTVALUEITERATOR(n)                           _qt5xhb_isObjectDerivedFrom(n,"QScriptValueIterator")

#define PQSCRIPTABLE(n)                                     (QScriptable *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTCLASS(n)                                    (QScriptClass *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTCLASSPROPERTYITERATOR(n)                    (QScriptClassPropertyIterator *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTCONTEXT(n)                                  (QScriptContext *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTCONTEXTINFO(n)                              (QScriptContextInfo *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTENGINE(n)                                   (QScriptEngine *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTENGINEAGENT(n)                              (QScriptEngineAgent *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTEXTENSIONPLUGIN(n)                          (QScriptExtensionPlugin *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTPROGRAM(n)                                  (QScriptProgram *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTSTRING(n)                                   (QScriptString *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTSYNTAXCHECKRESULT(n)                        (QScriptSyntaxCheckResult *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTVALUE(n)                                    (QScriptValue *) _qt5xhb_itemGetPtr(n)
#define PQSCRIPTVALUEITERATOR(n)                            (QScriptValueIterator *) _qt5xhb_itemGetPtr(n)

#define OPQSCRIPTABLE(n,v)                                  ISNIL(n)? v : (QScriptable *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTCLASS(n,v)                                 ISNIL(n)? v : (QScriptClass *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTCLASSPROPERTYITERATOR(n,v)                 ISNIL(n)? v : (QScriptClassPropertyIterator *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTCONTEXT(n,v)                               ISNIL(n)? v : (QScriptContext *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTCONTEXTINFO(n,v)                           ISNIL(n)? v : (QScriptContextInfo *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTENGINE(n,v)                                ISNIL(n)? v : (QScriptEngine *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTENGINEAGENT(n,v)                           ISNIL(n)? v : (QScriptEngineAgent *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTEXTENSIONPLUGIN(n,v)                       ISNIL(n)? v : (QScriptExtensionPlugin *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTPROGRAM(n,v)                               ISNIL(n)? v : (QScriptProgram *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTSTRING(n,v)                                ISNIL(n)? v : (QScriptString *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTSYNTAXCHECKRESULT(n,v)                     ISNIL(n)? v : (QScriptSyntaxCheckResult *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTVALUE(n,v)                                 ISNIL(n)? v : (QScriptValue *) _qt5xhb_itemGetPtr(n)
#define OPQSCRIPTVALUEITERATOR(n,v)                         ISNIL(n)? v : (QScriptValueIterator *) _qt5xhb_itemGetPtr(n)

#endif /* QT5XHB_MACROS_QTSCRIPT_H */
