/*

  Qt5xHb - Bindings libraries for Harbour/xHarbour and Qt Framework 5

  Copyright (C) 2018 Marcos Antonio Gambeta <marcosgambeta AT outlook DOT com>

*/

/*
  DO NOT EDIT THIS FILE - the content is created using a source code generator
*/

#ifndef QTSVG_CH
#define QTSVG_CH

#endif /* QTSVG_CH */
